//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenArquitectura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePago
    {
        public int IdDetalle { get; set; }
        public string Mes { get; set; }
        public int Cantidad { get; set; }
        public int Inscripcion_ { get; set; }
        public int PagoExtra { get; set; }
        public int IdAlumno { get; set; }
        public int IdPago { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Pago Pago { get; set; }
    }
}
