//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenArquitectura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingreso
    {
        public int IdIngreso { get; set; }
        public int IdPago { get; set; }
        public int Subtotal { get; set; }
        public int IdEgreso { get; set; }
        public int TotalFinal { get; set; }
    
        public virtual Egreso Egreso { get; set; }
        public virtual Pago Pago { get; set; }
    }
}
